# Generated by Django 5.0.8 on 2025-08-17 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        help_text="Code of the payment provider used",
                        max_length=50,
                        verbose_name="payment provider",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment ID from the payment provider",
                        max_length=255,
                        verbose_name="external payment ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar"), ("GBP", "British Pound")],
                        default="EUR",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True,
                        help_text="Raw request data sent to payment provider",
                        null=True,
                        verbose_name="raw request data",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response data from payment provider",
                        null=True,
                        verbose_name="raw response data",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for payment failure",
                        verbose_name="failure reason",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "authorized_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="authorized at"),
                ),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="captured at"),
                ),
                (
                    "failed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="failed at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("authorize", "Authorization"),
                            ("capture", "Capture"),
                            ("sale", "Sale"),
                            ("refund", "Refund"),
                            ("void", "Void"),
                            ("webhook", "Webhook Notification"),
                        ],
                        max_length=20,
                        verbose_name="transaction type",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                        verbose_name="external transaction ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="EUR", max_length=3, verbose_name="currency"
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="success")),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True,
                        help_text="Raw request data for this transaction",
                        null=True,
                        verbose_name="raw request data",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw response data for this transaction",
                        null=True,
                        verbose_name="raw response data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "db_table": "payments_transaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
