# Generated by Django 5.0.8 on 2025-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="ES", max_length=2, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default address for this type",
                verbose_name="default address",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=100, verbose_name="state/province"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address for the user",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("user", "type", "is_default")},
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "type"),
                name="unique_default_address_per_type",
            ),
        ),
    ]
